### PR TITLE
Fade out depth visualization between 4-5 meters, hiding anything further

### PR DESCRIPTION
**Pull request by hobinjk-ptc**

### CODE REVIEW

**Comment by benptc** [comment]
Actually can we tighten the fade from 4.5 meters to 5 instead of 4 to 5? Or how could I change that myself to experiment?

**Comment by hobinjk-ptc** [comment]
(with this the fade goes from 4-5 to 9-10 since it's still clamping the output from 0.0 to 1.0 so I multiply depth by 2 to make that be from 4.5-5.0)

**Comment by benptc** [comment]
Thanks!

**Review by benptc — APPROVED** [review]

**Comment by hobinjk-ptc** [comment]
If anything is broken on depth-representation it's because I pushed a minor adjustment to depth-representation which factors out the 2.0 from the alphaDepth formula to make it a bit clearer

**Pull request merged**
